# application-prod.yml
# 用于生产环境，推荐使用 PostgreSQL 数据库
# 如需切换为 MySQL，请参考 application-mysql.yml
spring:
  datasource:
    url: jdbc:postgresql://your-prod-db-host:5432/owner_voting_prod
    username: produser
    password: prodpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
# 说明：如需使用MySQL，请参考 application-mysql.yml 