# application-postgres.yml
# 用于生产或测试环境，使用 PostgreSQL（Supabase）数据库
# 如需切换为 MySQL，请参考 application-mysql.yml
spring:
  datasource:
    url: jdbc:postgresql://db.supabase.co:5432/yourdb
    username: youruser
    password: yourpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration 